# 부산항만공사_외내항컨테이너통합집계정보

### 북항, 신항 환적 효율성
- 'data.csv'가 북항/신항이 환적항으로 얼마나 효율적으로 운영되는가 라는 질문에 답할 수 있는 데이터인가?

In [1]:
import pandas as pd

TARGET_PATH = '../data/data.csv'

In [2]:
df = pd.read_csv(TARGET_PATH, encoding='euc-kr')
df

,연도,월,분기,청코드,내외항구분,수출입구분명,시설코드,시설명,부두구분명,아외국구분,적공구분,컨테이너수(10피트),컨테이너수(20피트),컨테이너수(40피트),컨테이너수(기타),전체개수,전체물동량
0,2024,3,1,신항,외항,수입,6,신항 W 정박지,일반부두,외국선,적컨,0,3,8,0,11,19.00
1,2024,4,2,신항,외항,수입,6,신항 W 정박지,일반부두,아국선,적컨,0,9,3,0,12,15.00
2,2024,11,4,신항,외항,수입환적,7,신항 U 정박지,일반부두,아국선,공컨,0,1,0,0,1,1.00
3,2024,11,4,신항,외항,수입,7,신항 U 정박지,일반부두,아국선,공컨,0,57,2,0,59,61.00
4,2024,11,4,신항,외항,수입환적,7,신항 U 정박지,일반부두,아국선,적컨,0,31,100,0,131,231.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2404,2024,7,3,북항,외항,수입환적,8,자성대 부두,컨테이너부두,외국선,적컨,0,8769,6434,0,15203,21637.00
2405,2024,7,3,북항,외항,수출,8,자성대 부두,컨테이너부두,외국선,적컨,0,7719,6438,2,14159,20599.50
2406,2024,7,3,북항,외항,수입,8,자성대 부두,컨테이너부두,외국선,적컨,0,7818,7253,0,15071,22324.00
2407,2024,11,4,북항,외항,수출,8,자성대 부두,컨테이너부두,외국선,적컨,0,2519,2018,3,4540,6561.75
2408,2024,11,4,북항,외항,수입,8,자성대 부두,컨테이너부두,외국선,적컨,0,4651,3613,0,8264,11877.00

In [3]:
df.shape

(2409, 17)

In [4]:
df.head()

,연도,월,분기,청코드,내외항구분,수출입구분명,시설코드,시설명,부두구분명,아외국구분,적공구분,컨테이너수(10피트),컨테이너수(20피트),컨테이너수(40피트),컨테이너수(기타),전체개수,전체물동량
0,2024,3,1,신항,외항,수입,6,신항 W 정박지,일반부두,외국선,적컨,0,3,8,0,11,19.0
1,2024,4,2,신항,외항,수입,6,신항 W 정박지,일반부두,아국선,적컨,0,9,3,0,12,15.0
2,2024,11,4,신항,외항,수입환적,7,신항 U 정박지,일반부두,아국선,공컨,0,1,0,0,1,1.0
3,2024,11,4,신항,외항,수입,7,신항 U 정박지,일반부두,아국선,공컨,0,57,2,0,59,61.0
4,2024,11,4,신항,외항,수입환적,7,신항 U 정박지,일반부두,아국선,적컨,0,31,100,0,131,231.0

In [5]:
df.columns.to_list()

['연도',
 '월',
 '분기',
 '청코드',
 '내외항구분',
 '수출입구분명',
 '시설코드',
 '시설명',
 '부두구분명',
 '아외국구분',
 '적공구분',
 '컨테이너수(10피트)',
 '컨테이너수(20피트)',
 '컨테이너수(40피트)',
 '컨테이너수(기타)',
 '전체개수',
 '전체물동량']

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2409 entries, 0 to 2408
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   연도           2409 non-null   int64
 1   월            2409 non-null   int64
 2   분기           2409 non-null   int64
 3   청코드          2409 non-null   str
 4   내외항구분        2409 non-null   str
 5   수출입구분명       2409 non-null   str
 6   시설코드         2409 non-null   int64
 7   시설명          2409 non-null   str
 8   부두구분명        2409 non-null   str
 9   아외국구분        2409 non-null   str
 10  적공구분         2409 non-null   str
 11  컨테이너수(10피트)  2409 non-null   int64
 12  컨테이너수(20피트)  2409 non-null   int64
 13  컨테이너수(40피트)  2409 non-null   int64
 14  컨테이너수(기타)    2409 non-null   int64
 15  전체개수         2409 non-null   int64
 16  전체물동량        2409 non-null   float64
dtypes: float64(1), int64(9), str(7)
memory usage: 320.1 KB

In [7]:
df['연도'].unique()

array([2024])

In [8]:
for col in ['청코드','내외항구분','수출입구분명','아외국구분','적공구분','부두구분명']:
    print(col,':', df[col].unique())
    print()

청코드 : <StringArray>
['신항', '북항', '감천']
Length: 3, dtype: str

내외항구분 : <StringArray>
['외항']
Length: 1, dtype: str

수출입구분명 : <StringArray>
['수입', '수입환적', '수출환적', '수출']
Length: 4, dtype: str

아외국구분 : <StringArray>
['외국선', '아국선']
Length: 2, dtype: str

적공구분 : <StringArray>
['적컨', '공컨']
Length: 2, dtype: str

부두구분명 : <StringArray>
['일반부두', '컨테이너부두']
Length: 2, dtype: str

In [9]:
#데이터가 동일하게 있어야 비교가 가능

df.groupby(['청코드','월']).size().unstack(level=0)

청코드  감천  북항   신항
월
1     7  87   97
2     9  87  101
3    11  94   98
4     8  77  107
5    13  75  113
6     9  70  110
7    10  79  116
8     8  70  112
9     7  89  114
10    8  84  116
11    9  93  117
12   10  86  108

In [10]:
df.groupby(['청코드','월']).size().unstack(level=0)

청코드  감천  북항   신항
월
1     7  87   97
2     9  87  101
3    11  94   98
4     8  77  107
5    13  75  113
6     9  70  110
7    10  79  116
8     8  70  112
9     7  89  114
10    8  84  116
11    9  93  117
12   10  86  108

In [11]:
df['전체물동량'].isna().sum()

np.int64(0)

In [12]:
df.isna()

,연도,월,분기,청코드,내외항구분,수출입구분명,시설코드,시설명,부두구분명,아외국구분,적공구분,컨테이너수(10피트),컨테이너수(20피트),컨테이너수(40피트),컨테이너수(기타),전체개수,전체물동량
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2404,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2405,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2406,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2407,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2408,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [13]:
df.describe()

,연도,월,분기,시설코드,컨테이너수(10피트),컨테이너수(20피트),컨테이너수(40피트),컨테이너수(기타),전체개수,전체물동량
count,2409.0,2409.000000,2409.000000,2409.000000,2409.000000,2409.000000,2409.000000,2409.000000,2409.000000,2409.000000
mean,2024.0,6.593192,2.529680,11.799087,2.574097,2357.080531,3865.119967,18.185969,6242.960565,10129.522623
std,0.0,3.462982,1.124354,7.905031,13.428490,3874.324901,7842.387127,54.339276,11470.764156,19308.235586
min,2024.0,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000
25%,2024.0,4.000000,2.000000,8.000000,0.000000,44.000000,84.000000,0.000000,154.000000,240.000000
50%,2024.0,7.000000,3.000000,9.000000,0.000000,407.000000,889.000000,0.000000,1381.000000,2316.500000
75%,2024.0,10.000000,4.000000,14.000000,0.000000,3190.000000,3932.000000,6.000000,7027.000000,11131.250000
max,2024.0,12.000000,4.000000,31.000000,132.000000,26277.000000,60733.000000,541.000000,82897.000000,144125.000000

### 목표
- 환적을 얼마나 많이 하는가?(규모) // 환적 비중 파악
- 환적을 얼마나 효율적으로 처리하는가?(효율) // 같은 리프트 횟수로 더 많은 TEU를 처리(TEU Facter)

In [15]:
# 환적 비중 계산(수출입구분명)

df['환적여부'] = df['수출입구분명'].isin(['수입환적', '수출환적'])
df

#2024년의 데이터이기 때문에 수출입 환적에 대한 대표성을 정의하기 어렵다.

,연도,월,분기,청코드,내외항구분,수출입구분명,시설코드,시설명,부두구분명,아외국구분,적공구분,컨테이너수(10피트),컨테이너수(20피트),컨테이너수(40피트),컨테이너수(기타),전체개수,전체물동량,환적여부
0,2024,3,1,신항,외항,수입,6,신항 W 정박지,일반부두,외국선,적컨,0,3,8,0,11,19.00,False
1,2024,4,2,신항,외항,수입,6,신항 W 정박지,일반부두,아국선,적컨,0,9,3,0,12,15.00,False
2,2024,11,4,신항,외항,수입환적,7,신항 U 정박지,일반부두,아국선,공컨,0,1,0,0,1,1.00,True
3,2024,11,4,신항,외항,수입,7,신항 U 정박지,일반부두,아국선,공컨,0,57,2,0,59,61.00,False
4,2024,11,4,신항,외항,수입환적,7,신항 U 정박지,일반부두,아국선,적컨,0,31,100,0,131,231.00,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2404,2024,7,3,북항,외항,수입환적,8,자성대 부두,컨테이너부두,외국선,적컨,0,8769,6434,0,15203,21637.00,True
2405,2024,7,3,북항,외항,수출,8,자성대 부두,컨테이너부두,외국선,적컨,0,7719,6438,2,14159,20599.50,False
2406,2024,7,3,북항,외항,수입,8,자성대 부두,컨테이너부두,외국선,적컨,0,7818,7253,0,15071,22324.00,False
2407,2024,11,4,북항,외항,수출,8,자성대 부두,컨테이너부두,외국선,적컨,0,2519,2018,3,4540,6561.75,False
2408,2024,11,4,북항,외항,수입,8,자성대 부두,컨테이너부두,외국선,적컨,0,4651,3613,0,8264,11877.00,False

In [16]:
zone_total = df.groupby('청코드')['전체물동량'].sum()
zone_total

청코드
감천        9014.0
북항     6512510.0
신항    17880496.0
Name: 전체물동량, dtype: float64

In [17]:
zone_transship = df[df['환적여부']].groupby('청코드')['전체물동량'].sum()
zone_transship

청코드
감천        6192.00
북항     2314512.75
신항    11176479.25
Name: 전체물동량, dtype: float64

In [18]:
zone_share = (zone_transship/zone_total *100).round(2)
zone_share

#신항의 환적 비중이 북항의 환적 비중보다 높다는 것을 알 수 있음

청코드
감천    68.69
북항    35.54
신항    62.51
Name: 전체물동량, dtype: float64

In [19]:
df.columns

Index(['연도', '월', '분기', '청코드', '내외항구분', '수출입구분명', '시설코드', '시설명', '부두구분명',
       '아외국구분', '적공구분', '컨테이너수(10피트)', '컨테이너수(20피트)', '컨테이너수(40피트)',
       '컨테이너수(기타)', '전체개수', '전체물동량', '환적여부'],
      dtype='str')

In [20]:
teu_estimate = df['컨테이너수(10피트)'] * 0.5 + df['컨테이너수(20피트)'] * 1 + df['컨테이너수(40피트)'] * 2
teu_estimate

0          19.0
1          15.0
2           1.0
3          61.0
4         231.0
         ...
2404    21637.0
2405    20595.0
2406    22324.0
2407     6555.0
2408    11877.0
Length: 2409, dtype: float64

In [21]:
teu_estimate.corr(df['전체물동량'])

#상광계수가 1에 거의 수렴하고, 컨테이너수(기타)를 어떻게 계산했는지 모르기 때문에 제외하였다.

np.float64(0.9999898787140992)

In [22]:
grp = df.groupby(['청코드','환적여부']).agg(물동량=('전체물동량','sum'), 개수=('전체개수','sum'))
grp['TEU_FACTOR'] = grp['물동량'] / grp['개수']

grp

                   물동량       개수  TEU_FACTOR
청코드 환적여부
감천  False      2822.00     1516    1.861478
    True       6192.00     3210    1.928972
북항  False   4197997.25  2859718    1.467976
    True    2314512.75  1569611    1.474577
신항  False   6704016.75  4140278    1.619219
    True   11176479.25  6464959    1.728778

## 적공구분(공컨비율 파악)

In [48]:
grp2 = df.groupby(['청코드', '환적여부', '적공구분'])['전체물동량'].sum().unstack(fill_value=0)

grp2

적공구분              공컨           적컨
청코드 환적여부
감천  False     1083.0      1739.00
    True         0.0      6192.00
북항  False  1314340.5   2883656.75
    True     45790.0   2268722.75
신항  False  1983822.0   4720194.75
    True    713056.0  10463423.25

In [51]:
grp2['공컨비율(%)'] = ((grp2['공컨'] / (grp2['공컨'] + grp2['적컨'])) * 100).round(2)

grp2
#신항의 공컨 비율이 북항의 공컨 비율보다 높다.

적공구분              공컨           적컨  공컨비율(%)
청코드 환적여부
감천  False     1083.0      1739.00    38.38
    True         0.0      6192.00     0.00
북항  False  1314340.5   2883656.75    31.31
    True     45790.0   2268722.75     1.98
신항  False  1983822.0   4720194.75    29.59
    True    713056.0  10463423.25     6.38

### 시각화

In [26]:
import plotly.express as px

In [32]:
grp

                   물동량       개수  TEU_FACTOR
청코드 환적여부
감천  False      2822.00     1516    1.861478
    True       6192.00     3210    1.928972
북항  False   4197997.25  2859718    1.467976
    True    2314512.75  1569611    1.474577
신항  False   6704016.75  4140278    1.619219
    True   11176479.25  6464959    1.728778

In [31]:
grp_plot = grp.reset_index()
grp_plot['환적여부'] = grp_plot['환적여부'].map({True:'환적', False:'수출입(일반)'})

grp_plot

  청코드     환적여부          물동량       개수  TEU_FACTOR
0  감천  수출입(일반)      2822.00     1516    1.861478
1  감천       환적      6192.00     3210    1.928972
2  북항  수출입(일반)   4197997.25  2859718    1.467976
3  북항       환적   2314512.75  1569611    1.474577
4  신항  수출입(일반)   6704016.75  4140278    1.619219
5  신항       환적  11176479.25  6464959    1.728778

In [33]:
grp_plot = grp_plot[grp_plot['청코드'] != '감천']
grp_plot

  청코드     환적여부          물동량       개수  TEU_FACTOR
2  북항  수출입(일반)   4197997.25  2859718    1.467976
3  북항       환적   2314512.75  1569611    1.474577
4  신항  수출입(일반)   6704016.75  4140278    1.619219
5  신항       환적  11176479.25  6464959    1.728778

In [34]:
fig = px.bar(grp_plot, x='청코드', y='TEU_FACTOR',color='환적여부', barmode='group', title='청코드, 환적여부 별 컨테이너당 TEU')
fig.show()

In [52]:
grp2_plot = grp2.reset_index()

In [53]:
grp2_plot['환적여부'] = grp2_plot['환적여부'].map({True:'환적', False:'수출입(일반)'})

In [54]:
grp2_plot = grp2_plot[grp2_plot['청코드'] != '감천']

In [55]:
fig = px.bar(grp2_plot, x='청코드', y='공컨비율(%)',color='환적여부', barmode='group', title='청코드, 환적여부 별 공컨비율')

fig.show()

물동량이 몰리는 달에도 우리가 구한 TEU_FACTOR와 같은 처리 효율 지표가 안정적으로 잘 유지된다면, 해당 항만은 물동량 변화에 잘 대응하는 여유있는 운영능력을 갖추었다고 판단할 수 있는 것이고, 반대로 물동량이 늘었을 때 효율이 떨어진다면 처리능력에 병목이 있다고 볼 수 있는 것이다.

In [35]:
df

,연도,월,분기,청코드,내외항구분,수출입구분명,시설코드,시설명,부두구분명,아외국구분,적공구분,컨테이너수(10피트),컨테이너수(20피트),컨테이너수(40피트),컨테이너수(기타),전체개수,전체물동량,환적여부
0,2024,3,1,신항,외항,수입,6,신항 W 정박지,일반부두,외국선,적컨,0,3,8,0,11,19.00,False
1,2024,4,2,신항,외항,수입,6,신항 W 정박지,일반부두,아국선,적컨,0,9,3,0,12,15.00,False
2,2024,11,4,신항,외항,수입환적,7,신항 U 정박지,일반부두,아국선,공컨,0,1,0,0,1,1.00,True
3,2024,11,4,신항,외항,수입,7,신항 U 정박지,일반부두,아국선,공컨,0,57,2,0,59,61.00,False
4,2024,11,4,신항,외항,수입환적,7,신항 U 정박지,일반부두,아국선,적컨,0,31,100,0,131,231.00,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2404,2024,7,3,북항,외항,수입환적,8,자성대 부두,컨테이너부두,외국선,적컨,0,8769,6434,0,15203,21637.00,True
2405,2024,7,3,북항,외항,수출,8,자성대 부두,컨테이너부두,외국선,적컨,0,7719,6438,2,14159,20599.50,False
2406,2024,7,3,북항,외항,수입,8,자성대 부두,컨테이너부두,외국선,적컨,0,7818,7253,0,15071,22324.00,False
2407,2024,11,4,북항,외항,수출,8,자성대 부두,컨테이너부두,외국선,적컨,0,2519,2018,3,4540,6561.75,False
2408,2024,11,4,북항,외항,수입,8,자성대 부두,컨테이너부두,외국선,적컨,0,4651,3613,0,8264,11877.00,False

In [40]:
sinhang = df[df['청코드'] == '신항']

monthly_sin = shinhang.groupby('월').agg(물동량=('전체물동량', 'sum'), 개수=('전체개수', 'sum'))

monthly_sin = monthly_sin.reset_index()
monthly_sin['TEU-FACTOR'] = monthly_sin['물동량'] / monthly_sin['개수']

monthly_sin

     월         물동량      개수  TEU-FACTOR
0    1  1416542.50  846609    1.673196
1    2  1356151.25  803971    1.686816
2    3  1563893.50  932734    1.676677
3    4  1492720.75  891671    1.674071
4    5  1554553.00  920312    1.689159
5    6  1531476.50  912843    1.677700
6    7  1558413.50  922562    1.689224
7    8  1526833.50  900600    1.695351
8    9  1382264.25  815262    1.695485
9   10  1518211.25  896472    1.693540
10  11  1449882.50  854701    1.696362
11  12  1529553.50  907500    1.685458

In [58]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

fig_dual = make_subplots(specs=[[{"secondary_y": True}]])

fig_dual.add_trace(go.Bar(x = monthly_sin['월'], y = monthly_sin['물동량'], name='물동량(TEU)'), secondary_y=False)

fig_dual.add_trace(go.Scatter(x = monthly_sin['월'], y = monthly_sin['TEU-FACTOR'], mode='lines+markers',name='TEU-FACTOR'), secondary_y=True)

#0.2의 차이에도 불구하고 그래프의 등락폭이 매우 크게 나타나 직접 범위를 지정해 주었다.
fig_dual.update_yaxes(secondary_y=True, range=[1.5, 1.8])

fig_dual.show()

#물동량이 늘어도 TEU팩터가 안정적으로 유지되고 있음을 알  수 있다.

### 회귀선 작성

In [60]:
import numpy as np

#y=wx + b // 가중치(기울기)와 편향(절편) 구하기
slope, intercept = np.polyfit(monthly_sin['물동량'], monthly_sin['TEU-FACTOR'], 1)

fig_scatter = go.Figure()

fig_scatter.add_trace(go.Scatter(x=monthly_sin['물동량'], y=monthly_sin['TEU-FACTOR'], mode='markers+text', text=monthly_sin['월'], name='월 별 관측치'))

x_range = [monthly_sin['물동량'].min(), monthly_sin['물동량'].max()]

#직선 그리기
fig_scatter.add_trace(go.Scatter(x=x_range, y=[ slope * x + intercept for x in x_range], mode='lines', name='회귀선'))

fig_scatter.show()

## KPI 설계

- 신항에 대한 환적 화물 TEU-FACTOR를 구하여 리프트당 처리 용적을 알 수 있고, 이 치수가 높을 수록 크레인과 야드의 생산성이 높다
- 신항과 북항에 대한 TEU-FACTOR 격차(%)를 비율로 보게되면 두 항에 대한 상대적 생산성 차이를 볼 수 있다.
- 환적화물 공컨비율의 신항 북항 대비 격차 - 낮을 수록 처리능력이 수익화물에 더 집중되어 있다고 볼 수 있다.
- (물동량과  teu팩터의 상관관계 파악)

In [61]:
grp

                   물동량       개수  TEU_FACTOR
청코드 환적여부
감천  False      2822.00     1516    1.861478
    True       6192.00     3210    1.928972
북항  False   4197997.25  2859718    1.467976
    True    2314512.75  1569611    1.474577
신항  False   6704016.75  4140278    1.619219
    True   11176479.25  6464959    1.728778

In [66]:
kpi_teu_factor_sinhang = grp.loc[('신항', True), 'TEU_FACTOR']
kpi_teu_factor

np.float64(1.7287780556690306)

In [67]:
kpi_teu_factor_bukhang = grp.loc[('북항', True), 'TEU_FACTOR']
kpi_teu_factor_bukhang

np.float64(1.4745772997258557)

In [68]:
kpi_teu_factor_gap = (kpi_teu_factor_sinhang / kpi_teu_factor_bukhang - 1)*100
kpi_teu_factor_gap

np.float64(17.23888981543622)

In [69]:
grp2

적공구분              공컨           적컨  공컨비율(%)
청코드 환적여부
감천  False     1083.0      1739.00    38.38
    True         0.0      6192.00     0.00
북항  False  1314340.5   2883656.75    31.31
    True     45790.0   2268722.75     1.98
신항  False  1983822.0   4720194.75    29.59
    True    713056.0  10463423.25     6.38

In [70]:
kpi_empty_ratio_sinhang = grp2.loc[('신항', True), '공컨비율(%)']
kpi_empty_ratio_sinhang

np.float64(6.38)

In [71]:
kpi_empty_ratio_bukhang = grp2.loc[('북항', True), '공컨비율(%)']
kpi_empty_ratio_bukhang

np.float64(1.98)